### PR TITLE
Roster + Menulocation Improvements

### PR DESCRIPTION
**Pull request by JordanLeich**
- OHS now works with the 36 Roster Hack Gold Edition mod. Players can now swap in and out characters while keeping the same menu location order as the 36 Roster Hack Gold Edition mod.
- Added a new X-Men only roster.

### CODE REVIEW

**Comment by TheRealPSV** [comment]
Thanks for the contribution. Can you tell me what you're referring to with the 36 Gold Edition mod? Is it just the extra stage included with the 36 roster hack?

I'd rather not include the X-Men roster, as custom/specialty roster lists are outside the scope of this repo. I only include menulocations for each particular hack, and the only roster provided with the project is the one that corresponds to the Official Characters Pack.

**Comment by JordanLeich** [comment]
> Thanks for the contribution. Can you tell me what you're referring to with the 36 Gold Edition mod? Is it just the extra stage included with the 36 roster hack?

Yes, the 36 roster hack comes with an optional gold edition stage and places 36 ocp characters into the same order as they would appear in if you were using the gold edition version of the game. The issue though is that when you want to swap characters in and out when using OHS and the gold edition stage is that the characters get all messed up because there's no menu locations file for that stage which is what I created. With the menu locations file I created, players can now swap in and out characters while using the gold edition stage without having to worry about the stage getting bugged out.

> I'd rather not include the X-Men roster, as custom/specialty roster lists are outside the scope of this repo. I only include menulocations for each particular hack, and the only roster provided with the project is the one that corresponds to the Official Characters Pack.

Ok that's fair I understand, I'll just keep the X-Men only roster to myself or release it separately on its own as a herostat mod.

**Comment by JordanLeich** [comment]
Also I forgot to mention that the X-Men roster I made only corresponds with the ocp mod and not any other modded characters. Not sure if that matters or not if you want to include that into OHS but let me know.

**Comment by TheRealPSV** [comment]
> Also I forgot to mention that the X-Men roster I made only corresponds with the ocp mod and not any other modded characters. Not sure if that matters or not if you want to include that into OHS but let me know.

No, it still wouldn't make sense to include it. Maybe things like that could be added to some kind of rosters database somewhere separately.

Also, can you delete your Roster.cfg file for the 36 characters as well? The only thing needed should be the menulocations. If you need to, modify that menulocations to correspond to the default roster file.

**Comment by JordanLeich** [comment]
Ok the roster.cfg file is deleted now. Only new change should be the new menulocations file.

**Comment by TheRealPSV** [comment]
Merged, thanks. I'll include this in the next update.

**Pull request merged**
